language: elixir
elixir:
  - 1.4.5
otp_release:
  - 19.3
  - 20.0
script:
  - mix test --no-start --trace --cover --exclude integration
  - MIX_ENV=test mix credo --strict
  - cd test/integration
  - mix deps.get
  - mix test --no-start --trace
services:
  - redis-server
sudo: false
